spring:
  pizzacloud:
    api:
      url: http://localhost:8080/api/orders/fromEmail
    email:
      host: imap.gmail.com
      mailbox: INBOX
      username: pizzacloud
      password: password
      poll-rate: 3000
  main:
    web-application-type: none






