


spring:
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: pizza-cloud
  security:
    user:
      name: user
      password: password
---
spring:
  datasource:
    url: jdbc:mysql://localhost/pizzacloud
    username: pizzaname
    password: pizzapassword
  config:
    activate:
      on-profile: prod

logging:
  level:
    tacos: WARN